services:
  postgres:
    image: postgres:15-alpine
    container_name: consignado-db
    ports:
      - "5432:5432"
    environment:
      POSTGRES_USER: consignado
      POSTGRES_PASSWORD: consignado
      POSTGRES_DB: consignado_db
    volumes:
      - postgres_data:/var/lib/postgresql/data

volumes:
  postgres_data:
