services:
  # Customer Service Database
  postgres-customer:
    image: postgres:15-alpine
    container_name: consignado-customer-db
    ports:
      - "5432:5432"
    environment:
      POSTGRES_USER: consignado
      POSTGRES_PASSWORD: consignado
      POSTGRES_DB: consignado_db
    volumes:
      - postgres_customer_data:/var/lib/postgresql/data

  # Simulation Service Cache
  redis:
    image: redis:7-alpine
    container_name: consignado-redis
    ports:
      - "6379:6379"
    command: redis-server --appendonly yes
    volumes:
      - redis_data:/data

volumes:
  postgres_customer_data:
  redis_data:
