spring:
  application:
    name: consignado-customer-service

  datasource:
    url: jdbc:postgresql://localhost:5432/consignado_db
    username: consignado
    password: consignado

  jpa:
    hibernate:
      ddl-auto: validate
    show-sql: true
    properties:
      hibernate:
        format_sql: true

  flyway:
    enabled: true

services:
  simulation:
    url: http://localhost:8081

springdoc:
  api-docs:
    path: /api-docs
  swagger-ui:
    path: /swagger-ui.html